- app/onboarding/category.tsx
> 둘다선택가능 문구추가

- components/exhibition/HorizontalSliding.tsx
- components/exhibition/RecommendForYou.tsx
> fix: 슬라이딩 오류 수정

- components/exhibition/HorizontalSliding.tsx
- components/exhibition/RecommendForYou.tsx
> fix: 무한 슬라이딩 오류 수정

- app/exhibition/[id].tsx
- components/ui/AutoHeightImage.tsx
fix: 안드로이드 화질 개선 (expo-image로 변경)
> fix: 안드로이드 화질 개선 (expo-image로 변경)

- components/exhibition/ExhibitionLogCard.tsx
> fix: 전시기록 탭 사진 출력 오류 수정

- app/(tabs)/exhibitionLog.tsx
- app/exhibition/write-record.tsx
- components/exhibition/ExhibitionLogCard.tsx
> fix: 전시기록 화면 비율 수정

- app/(tabs)/exhibitionLog.tsx
- app/exhibition/write-record.tsx
> chore: 몇분전에 전시 기록 되었는지 반영

- app/(tabs)/exhibitionLog.tsx
> feat: 최신순 전시 기록 정렬 구현

- app/(tabs)/exhibitionLog.tsx
- app/exhibition-log/[exhibitionLog-id].tsx
> feat: 전시기록에 댓글 작성 틀 생성

- app/(tabs)/exhibition-log/ExhibitionLogCard.tsx
- app/(tabs)/exhibition-log/[exhibitionLog-id].tsx
- app/(tabs)/exhibition-log/like/LikeButton.tsx
- app/(tabs)/exhibition-log/like/countLike.tsx
- app/_layout.tsx
- contexts/LikeContext.tsx
> feat: 좋아요 기능 구현(임시)

- app/(tabs)/exhibition-log/ExhibitionLogCard.tsx
- app/(tabs)/exhibition-log/[exhibitionLog-id].tsx
- app/(tabs)/exhibition-log/like/LikeButton.tsx
> chore: 전시 기록 탭 디자인 수정

- app/(tabs)/exhibition-log/[exhibitionLog-id].tsx
- app/(tabs)/mypage/exhibition/Bookmarked.tsx
- app/(tabs)/mypage/exhibition/thumbs-up.tsx
- app/(tabs)/mypage/exhibition/visited.tsx
- app/(tabs)/mypage/index.tsx
- app/exhibition/write-record.tsx
- contexts/ExhibitionContext.tsx
[fix: 좋아요 전시 방문한 전시 디자인, 경로 수정](https://github.com/lastro1206/jeonlog-frontend/commit/364680aa51515c02328f7757f88484b4f9ec9f31)
> fix: 좋아요 전시 방문한 전시 디자인, 경로 수정

- app/(tabs)/exhibition-log/[exhibitionLog-id].tsx
- app/(tabs)/exhibition-log/exhibitionLog.tsx
- app/(tabs)/mypage/exhibition/DeleteRecordButton.tsx
- app/(tabs)/mypage/index.tsx
- app/(tabs)/mypage/old-index.tsx
- app/(tabs)/mypage/setting.tsx
- app/exhibition/write-record.tsx
- contexts/ExhibitionContext.tsx
feat: myPage ui개선 및 전시기록 관련 exhibitionContext로 통일
> feat: myPage ui개선 및 전시기록 관련 exhibitionContext로 통일

- app/(tabs)/exhibition-log/ExhibitionLogCard.tsx
- app/(tabs)/exhibition-log/[exhibitionLog-id].tsx
- app/(tabs)/mypage/index.tsx
- contexts/ExhibitionContext.tsx
- contexts/LikeContext.tsx
[fix: 좋아요 오류 수정](https://github.com/lastro1206/jeonlog-frontend/commit/37adb2bf108cdae3bab8249d737ed59bcc3349a3)
> fix: 좋아요 오류 수정

- app/(tabs)/mypage/index.tsx
> fix: 마이페이지 디자인 수정

- app/(tabs)/mypage/index.tsx
> fix:마이페이지 디자인 수정

- app/(tabs)/category.tsx
- app/(tabs)/exhibition-log/exhibitionLog.tsx
- app/(tabs)/mypage/exhibition/visited.tsx
- app/(tabs)/mypage/setting.tsx
- design-system/styles/TopBarStyles.ts
fix: 전시기록 탭 상단 검색창 추가(기존 상단바 제거)
> fix: 전시기록 탭 상단 검색창 추가(기존 상단바 제거)

- app/(tabs)/exhibition-log/[exhibitionLog-id].tsx
- app/(tabs)/exhibition-log/exhibitionLog.tsx
- app/(tabs)/mypage/index.tsx
- app/exhibition/write-record.tsx
- contexts/ExhibitionContext.tsx
- package-lock.json
- package.json
> fix:이미지 추가, 출력 디자인 수정

- app/(tabs)/exhibition-log/ExhibitionLogCard.tsx
- app/(tabs)/exhibition-log/exhibitionLog.tsx
- app/(tabs)/mypage/edit-profile.tsx
- app/(tabs)/mypage/index.tsx
- app/(tabs)/mypage/setting.tsx
- design-system/styles/ExhibitionLogStyles.ts
- design-system/styles/MyPageStyles.ts
- design-system/styles/SettingStyles.ts
- design-system/styles/editProfileStyles.ts
> feat: 프로필 수정 구현

- app/(tabs)/Home.styles.ts
- app/(tabs)/home.tsx
- app/(tabs)/mypage/index.tsx
- components/exhibition/HorizontalSliding.tsx
- components/exhibition/RecommendForYou.tsx
- components/ui/TopBar.tsx
- design-system/components/Button.tsx
- design-system/components/Text.tsx
- design-system/styles/ExhibitionLogStyles.ts
- design-system/styles/TopBarStyles.ts
> fix: 디자인 수정

- app/(tabs)/Home.styles.ts
- app/(tabs)/mypage/index.tsx
- app/(tabs)/search.tsx
> chore:디자인 수정
